/*
Copyright 2018 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVolumeImports implements VolumeImportInterface
type FakeVolumeImports struct {
	Fake *FakeStorkV1alpha1
	ns   string
}

var volumeimportsResource = schema.GroupVersionResource{Group: "stork.libopenstorage.org", Version: "v1alpha1", Resource: "volumeimports"}

var volumeimportsKind = schema.GroupVersionKind{Group: "stork.libopenstorage.org", Version: "v1alpha1", Kind: "VolumeImport"}

// Get takes name of the volumeImport, and returns the corresponding volumeImport object, and an error if there is any.
func (c *FakeVolumeImports) Get(name string, options v1.GetOptions) (result *v1alpha1.VolumeImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(volumeimportsResource, c.ns, name), &v1alpha1.VolumeImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeImport), err
}

// List takes label and field selectors, and returns the list of VolumeImports that match those selectors.
func (c *FakeVolumeImports) List(opts v1.ListOptions) (result *v1alpha1.VolumeImportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(volumeimportsResource, volumeimportsKind, c.ns, opts), &v1alpha1.VolumeImportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VolumeImportList{ListMeta: obj.(*v1alpha1.VolumeImportList).ListMeta}
	for _, item := range obj.(*v1alpha1.VolumeImportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested volumeImports.
func (c *FakeVolumeImports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(volumeimportsResource, c.ns, opts))

}

// Create takes the representation of a volumeImport and creates it.  Returns the server's representation of the volumeImport, and an error, if there is any.
func (c *FakeVolumeImports) Create(volumeImport *v1alpha1.VolumeImport) (result *v1alpha1.VolumeImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(volumeimportsResource, c.ns, volumeImport), &v1alpha1.VolumeImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeImport), err
}

// Update takes the representation of a volumeImport and updates it. Returns the server's representation of the volumeImport, and an error, if there is any.
func (c *FakeVolumeImports) Update(volumeImport *v1alpha1.VolumeImport) (result *v1alpha1.VolumeImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(volumeimportsResource, c.ns, volumeImport), &v1alpha1.VolumeImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeImport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVolumeImports) UpdateStatus(volumeImport *v1alpha1.VolumeImport) (*v1alpha1.VolumeImport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(volumeimportsResource, "status", c.ns, volumeImport), &v1alpha1.VolumeImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeImport), err
}

// Delete takes name of the volumeImport and deletes it. Returns an error if one occurs.
func (c *FakeVolumeImports) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(volumeimportsResource, c.ns, name), &v1alpha1.VolumeImport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVolumeImports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(volumeimportsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.VolumeImportList{})
	return err
}

// Patch applies the patch and returns the patched volumeImport.
func (c *FakeVolumeImports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VolumeImport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(volumeimportsResource, c.ns, name, data, subresources...), &v1alpha1.VolumeImport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VolumeImport), err
}
