# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.11.2"
  revision = "6702109cc68eb6fe6350b83e14407c8d7309fd1a"


[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.2"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.4"

[[override]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  # branch = "master" #osdk_branch_annotation
  version = "=v0.1.0" #osdk_version_annotation

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false

## temp once, for migration purpose

[[override]]
  name = "github.com/libopenstorage/autopilot-api"
  source = "github.com/saheienko/autopilot-api"
  branch = "update-operator-sdk"

## other packages

[[override]]
  name = "github.com/kubernetes-incubator/external-storage"
  source = "github.com/libopenstorage/external-storage"
  branch = "openstorage-5.1"

[[override]]
  name = "github.com/libopenstorage/openstorage"
  branch = "release-7.0"

[[override]]
  name = "github.com/portworx/sched-ops"
  branch = "kubernetes-1.11"

[[constraint]]
  branch = "master"
  name = "github.com/portworx/torpedo"

[[constraint]]
  name = "github.com/heptio/ark"
  version = "v1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/skyrings/skyring-common"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[constraint]]
  name = "gocloud.dev"
  version = "0.13.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"
