# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/kube-openapi/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "sigs.k8s.io/controller-tools/pkg/crd/generator",
]

[[override]]
  name = "k8s.io/code-generator"
  # revision for tag "kubernetes-1.13.1"
  revision = "c2090bec4d9b1fb25de3812f868accc2bc9ecbae"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.6"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.13.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.6"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.10"

[[override]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.10.1" 

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[override]]
  name = "github.com/go-openapi/spec"
  branch = "master"

[[override]]
  name = "sigs.k8s.io/controller-tools"
  revision = "9d55346c2bde73fb3326ac22eac2e5210a730207"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.29.0"

[[override]]
  name = "k8s.io/kube-state-metrics"
  version = "v1.6.0"

[prune]
  go-tests = true
  non-go = true

[[prune.project]]
  name = "k8s.io/code-generator"
  non-go = false

## temp once, for migration purpose

[[override]]
  name = "github.com/portworx/sched-ops"
  source = "github.com/saheienko/sched-ops"
  branch = "k8s-backward-compatibility"

## other packages

[[override]]
  name = "github.com/kubernetes-incubator/external-storage"
  source = "github.com/saheienko/external-storage"
  branch = "openstorage-5.5"

[[override]]
  name = "github.com/kubernetes-sigs/sig-storage-lib-external-provisioner" 
  revision = "712c5819bca548e64c5fb29d2946c5d69126c3fa"

[[override]]
  name = "github.com/libopenstorage/openstorage"
  branch = "release-7.0"

[[constraint]]
  branch = "master"
  name = "github.com/portworx/torpedo"

[[constraint]]
  name = "github.com/heptio/ark"
  version = "v1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/skyrings/skyring-common"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "ea233b6412b0421a65dc6160e16c893364664a95"

[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[constraint]]
  name = "gocloud.dev"
  version = "0.13.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[override]]
  name = "github.com/libopenstorage/secrets"
  branch = "master"

[[override]]
  name = "github.com/openshift/api"
  revision = "d2f01e7b77a6fc78b328db20285423838419fef7"

[[override]]
  name = "github.com/openshift/client-go"
  revision = "7cc0953bbbb7925e30232c056606d666942bb542"

