/*
Copyright 2018 Openstorage.org

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/libopenstorage/stork/pkg/apis/stork/v1alpha1"
	scheme "github.com/libopenstorage/stork/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VolumeImportsGetter has a method to return a VolumeImportInterface.
// A group's client should implement this interface.
type VolumeImportsGetter interface {
	VolumeImports(namespace string) VolumeImportInterface
}

// VolumeImportInterface has methods to work with VolumeImport resources.
type VolumeImportInterface interface {
	Create(*v1alpha1.VolumeImport) (*v1alpha1.VolumeImport, error)
	Update(*v1alpha1.VolumeImport) (*v1alpha1.VolumeImport, error)
	UpdateStatus(*v1alpha1.VolumeImport) (*v1alpha1.VolumeImport, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.VolumeImport, error)
	List(opts v1.ListOptions) (*v1alpha1.VolumeImportList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VolumeImport, err error)
	VolumeImportExpansion
}

// volumeImports implements VolumeImportInterface
type volumeImports struct {
	client rest.Interface
	ns     string
}

// newVolumeImports returns a VolumeImports
func newVolumeImports(c *StorkV1alpha1Client, namespace string) *volumeImports {
	return &volumeImports{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the volumeImport, and returns the corresponding volumeImport object, and an error if there is any.
func (c *volumeImports) Get(name string, options v1.GetOptions) (result *v1alpha1.VolumeImport, err error) {
	result = &v1alpha1.VolumeImport{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("volumeimports").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VolumeImports that match those selectors.
func (c *volumeImports) List(opts v1.ListOptions) (result *v1alpha1.VolumeImportList, err error) {
	result = &v1alpha1.VolumeImportList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("volumeimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested volumeImports.
func (c *volumeImports) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("volumeimports").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a volumeImport and creates it.  Returns the server's representation of the volumeImport, and an error, if there is any.
func (c *volumeImports) Create(volumeImport *v1alpha1.VolumeImport) (result *v1alpha1.VolumeImport, err error) {
	result = &v1alpha1.VolumeImport{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("volumeimports").
		Body(volumeImport).
		Do().
		Into(result)
	return
}

// Update takes the representation of a volumeImport and updates it. Returns the server's representation of the volumeImport, and an error, if there is any.
func (c *volumeImports) Update(volumeImport *v1alpha1.VolumeImport) (result *v1alpha1.VolumeImport, err error) {
	result = &v1alpha1.VolumeImport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("volumeimports").
		Name(volumeImport.Name).
		Body(volumeImport).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *volumeImports) UpdateStatus(volumeImport *v1alpha1.VolumeImport) (result *v1alpha1.VolumeImport, err error) {
	result = &v1alpha1.VolumeImport{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("volumeimports").
		Name(volumeImport.Name).
		SubResource("status").
		Body(volumeImport).
		Do().
		Into(result)
	return
}

// Delete takes name of the volumeImport and deletes it. Returns an error if one occurs.
func (c *volumeImports) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("volumeimports").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *volumeImports) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("volumeimports").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched volumeImport.
func (c *volumeImports) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.VolumeImport, err error) {
	result = &v1alpha1.VolumeImport{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("volumeimports").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
